### ISSUE TITLE
Comment and Question: What's the best way to use Jelly from Actix-web or Rocket?

### ISSUE THREAD

**Issue by digeratus** [secretkeysio/jelly-actix-web-starter#1]
Can't thank you enough for this project. I agree, all web frameworks should have a similar solution. Glad there's now one for Rust. Now the question is, how to use it from other Rust frameworks such as Rocket. If I'm not mistaken actix-web is included in the toml file as a library so that should be pretty straight forward, but what about Rocket?

Thanks.

**Comment by ryanmcgrath** [comment]
You'd want to fork this and swap out the relevant pieces in `jelly/server.rs` for Rocket-specific parts, I guess, and then update the view handling in `accounts/views` to Rocket-specific pieces. The rest could theoretically bolt on pretty well, I think.

I'm not a Rocket user so I can't weigh in too much, but if someone wants to fork this to do it for Rocket, feel free (or if Rocket could find a way to do this kind of thing by-default in the framework it'd be amazing).

I'll leave this open for now in case people want to discuss and throw ideas around.

**Comment by digeratus** [comment]
Thank you
