### ISSUE TITLE
have smtp as a mail option in addition to Postmark, SMTP is a very standard way to send mail.

### ISSUE THREAD

**Issue by Jieiku** [secretkeysio/jelly-actix-web-starter#17]
I am suggesting the jelly-actix-web-starter also allow sending mail via a configurable SMTP account.

I am currently working to implement this without removing any of the Postmark related stuff.

A lot of developers are familiar with SMTP but may have never used the Postmark service before.

I was thinking jelly application could look for the presence of a POSTMARK_API_KEY and if missing use SMTP instead.

The two smtp crates that caught my eye so far are mail-smtp and lettre.

mail-smtp uses tokio-smtp: https://crates.io/crates/mail-smtp

lettre: https://github.com/lettre/lettre

I am still trying to compare the two before I implement one. I can issue a pull request once I finish this if it would interest you?

Are there any SMTP crates you have used? any you would recommend?

**Comment by ryanmcgrath** [comment]
I’ve used Lettre and don’t mind it, I just wouldn’t use pure local mail to run a site in 2020 - mail deliverability is a pain in the ass to handle and I always outsource it.

That said, sure, I’d accept a PR - others might want it. I wanted to feature flag Postmark to make setup more intuitive anyway...

Maybe feature flag these like “email/postmark” and “email/sendmail” or something? Should just need to replace the Email struct implementation that way. Others could PR their email framework of choice this way, too.

**Comment by mikeumus** [comment]
Yeah, Lettre sounds like a good default so people don't experience this:
<img width="727" alt="Screen Shot 2021-05-13 at 3 01 20 AM" src="https://user-images.githubusercontent.com/57934/118090745-ea767f00-b397-11eb-9b05-35737ff002d9.png">

Also, Lettre is Rust! 🦀

**Comment by xekon** [comment]
I started on this, and in `jelly/Cargo.toml` I added:

[dependencies]
...
lettre = { version = "0.10.0-beta.4", optional = true }
...

[features]
email_smtp = ["lettre"]

however up on level in the frontend app: 'Cargo.toml' there is this:

[features]
default = ["jelly/template_watcher", "jelly/static"]
production = ["jelly/production"]

so to make use of the email_smtp that is part of jelly, would I need to do something like below or is there a cleaner way?

jelly/Cargo.toml:

[dependencies]
...
lettre = { version = "0.10.0-beta.4", optional = true }
...

[features]
production_postmark = ["actix-web/secure-cookies", "djangohashers/pbkdf2" ]
production_smtp = ["actix-web/secure-cookies", "djangohashers/pbkdf2", "lettre" ]

and then up one level in Cargo.toml:
[features]
default = ["jelly/template_watcher", "jelly/static"]
production = ["jelly/production_smtp"]

**Comment by ryanmcgrath** [comment]
Fairly close, yeah - although I think I'd prefer `email-smtp`.

The current Postmark functionality should be moved behind a `email-postmark` feature flag, too - and probably just set the user as verified by default if no email backend feature is configured.

**Comment by xekon** [comment]
I have some of this functionality finished and did it as discussed here with feature flags.

Currently I have it using lettre and it properly connects with my smtp server and sends mail to the email of the newly registered user, HOWEVER I currently have a test string in place for the subject and body.

I am trying to understand from your example how that data is stored, I am guessing its from these:

```
    /// The template alias (e.g, 'verify-email`).
    #[serde(rename = "TemplateAlias")]
    pub alias: &'a str,

    /// Data that the template can use to render.
    #[serde(rename = "TemplateModel")]
    pub model: HashMap<&'a str, String>,
```

I am needing a string to pass to .subject and .body

I worked off the example from the lettre github readme, and converted it to a struct using your example for postmark.

Here is what I have so far for email.rs:
```
//! Provides a very, very basic `Email` struct that can send via Postmark.
//! This is designed for transactional emails - if you need otherwise,
//! you're free to import Lettre or whatever.
//!
//! If you prefer a different provider than Postmark, you can swap the
//! send implementation in here.
use std::collections::HashMap;
use std::env::var;
use log::{info};

use chrono::{Datelike, Utc};

#[cfg(feature = "email-postmark")]
use serde::{Serialize};

#[cfg(feature = "email-smtp")]
use lettre::transport::smtp::authentication::Credentials;
#[cfg(feature = "email-smtp")]
use lettre::{Message, SmtpTransport, Transport};

#[cfg(feature = "email-smtp")]
#[derive(Debug, Default)]
pub struct Email<'a> {
    /// The template alias (e.g, 'verify-email`).
    pub alias: &'a str,

    /// Data that the template can use to render.
    pub model: HashMap<&'a str, String>,

    /// Who's sending this.
    pub from: String,

    /// Who to send to. Comma-delimited.
    pub to: String,

    /// SMTP Host to relay mail through.
    pub host: String,

    /// username to authenticate with SMTP Host.
    pub username: String,

    /// password to authenticate with SMTP Host.
    pub password: String

}

#[cfg(feature = "email-smtp")]
impl<'a> Email<'a> {
    /// Construct a new `Email`.
    pub fn new(
        alias: &'a str,
        to: &[String],
        model: HashMap<&'a str, String>
    ) -> Self {
        Email {
            alias: alias,
            model: model,
            to: to.join(","),
            from: var("EMAIL_DEFAULT_FROM")
                .expect("EMAIL_DEFAULT_FROM not set!"),
            host: var("EMAIL_SMTP_HOST")
                .expect("EMAIL_SMTP_HOST not set!"),
            username: var("EMAIL_SMTP_USERNAME")
                .expect("EMAIL_SMTP_USERNAME not set!"),
            password: var("EMAIL_SMTP_PASSWORD")
                .expect("EMAIL_SMTP_PASSWORD not set!"),
        }
    }

    /// Send the email. Relies on you ensuring that `EMAIL_DEFAULT_FROM`,
    /// `EMAIL_SMTP_HOST`, `EMAIL_SMTP_USERNAME`, and `EMAIL_SMTP_PASSWORD`
    /// are set in your `.env`.
    pub fn send(mut self) -> Result<(), anyhow::Error> {
        let now = Utc::now();
        let year = now.year();
        self.model.insert("year", year.to_string());

        let email = Message::builder()
            .from(self.from.parse().unwrap())
            .reply_to(self.from.parse().unwrap())
            .to(self.to.parse().unwrap())
            .subject("Happy new year")
            .body(String::from("Be happy!"))
            .unwrap();

        let creds = Credentials::new(self.username.to_string(), self.password.to_string());

        info!("{}", self.model.to_string());
        // Open a remote connection to gmail
        let mailer = SmtpTransport::relay(&self.host.to_string())
            .unwrap()
            .credentials(creds)
            .build();

        mailer.send(&email)?;

        Ok(())
    }
}



/// Represents information that Postmark can use to send emails. This by
/// default relies on templates existing on the Postmark side - you'll send
/// less data over the wire this way.
#[cfg(feature = "email-postmark")]
#[derive(Debug, Default, Serialize)]
pub struct Email<'a> {
    /// The template alias (e.g, 'verify-email`).
    #[serde(rename = "TemplateAlias")]
    pub alias: &'a str,

    /// Data that the template can use to render.
    #[serde(rename = "TemplateModel")]
    pub model: HashMap<&'a str, String>,

    /// Who's sending this.
    #[serde(rename = "From")]
    pub from: String,

    /// Who to send to. Comma-delimited.
    #[serde(
        rename = "To"
    )]
    pub to: String
}

#[cfg(feature = "email-postmark")]
impl<'a> Email<'a> {
    /// Construct a new `Email`.
    pub fn new(
        alias: &'a str,
        to: &[String],
        model: HashMap<&'a str, String>
    ) -> Self {
        Email {
            alias: alias,
            model: model,
            to: to.join(","),
            from: var("EMAIL_DEFAULT_FROM")
                .expect("EMAIL_DEFAULT_FROM not set!")
        }
    }

    /// Send the email. Relies on you ensuring that `POSTMARK_API_KEY`
    /// is set in your `.env`.
    pub fn send(mut self) -> Result<(), anyhow::Error> {
        let now = Utc::now();
        let year = now.year();
        self.model.insert("year", year.to_string());

        let api_key = std::env::var("POSTMARK_API_KEY")
            .expect("POSTMARK_API_KEY not set!");

        minreq::post("https://api.postmarkapp.com/email/withTemplate")
            .with_header("X-Postmark-Server-Token", api_key)
            .with_json(&self)?.send()?;

        Ok(())
    }
}
```

**Comment by xekon** [comment]
I figured out how to check the contents of model:

```
        // some debug info
        for (key, value) in &self.model {
            info!("{}: {}", key, value);
        }
```

which outputs:
```
 INFO  jelly::email                       > year: 2021
 INFO  jelly::email                       > action_url: https://www.example.com:17001/accounts/reset/
 INFO  jelly::email                       > name: JakeG
 INFO  jelly::email                       > preview: Did you want to reset your password?
```

So it seems because of how the postmark service works, half the email formatting would be in a template on the postmark server.

The only data it would send are the parts of the email that changes.

I am assuming this means that for a real solution for SMTP I should not be trying to simply use the values stored within self.model and that I would probably need to alter the files in src/accounts/jobs so that if features:email-smtp is set then it passes a different value for model.

I am thinking for SMTP I would only have two model.insert  one for subject and one for body.

Does this sound about right? 

If there is a better way to implement this, then please let me know what you have in mind.

**Comment by ryanmcgrath** [comment]
Yeah, so the thing is, if you're running something in production, it's often desirable to have the template stored on the server - then you're only sending the args (model) over. Postmark _should_ support doing it by just sending the full payload, though, so...

What might be fine here is going ahead and building your SMTP solution with the templates rewritten to be Tera templates (they're currently Postmark templates) and then we can alter the Postmark side of things to just send the entire rendered template. Since this is more of a starter and less of a true framework, this is probably fine - anybody who needs to be sending just the model over can change it to be such.

**Comment by xekon** [comment]
Awesome, thank you for the response. Now I have a better idea of what to do going forward so that its a good pull request once i am done.

**Comment by matclab** [comment]
I've taken the liberty to do a tentative PR on this subject. Please do not hesitate to comment.

**Comment by xekon** [comment]
Awesome, my life just got far to hectic to get anything done lately. Will be sure to check it out as soon as I start working on my project again, thank you!

**Comment by Jieiku** [comment]
@matclab Works Great! I am using it now!

**Comment by Jieiku** [comment]
This https://github.com/secretkeysio/jelly-actix-web-starter/pull/19 is merged and works great for me! closing this now.
