### ISSUE TITLE
randomize style.css as style-0kj70fYG.css for cache busting every time jelly server is started?

### ISSUE THREAD

**Issue by Jieiku** [secretkeysio/jelly-actix-web-starter#29]
Currently in `templates/layout.html`
I have `<link rel="stylesheet" href="/style.css">`

I am wondering if every time I start the Jelly server if it could rename the file and serve a copy of the file with a randomized hash value or something to facilitate cache busting.

I could probably accomplish this via a custom bash script that does like mv /style*.css /style-random().css and then also use bash sed to replace the css filename in the template files and then finally start the server.... but I just want to make sure I am not doing things the hard way by doing it like that.

I know this is a general question and not specific to rust, so please do tell me if you would rather me not post these type of question here. I just thought I would ask in case you knew of a way in which rust would handle this internally, instead of relying on an external script.

It does look like rust can rename files.... so if I can get it to do that with a regex pattern then I can probably accomplish this. 

https://doc.rust-lang.org/std/fs/fn.rename.html

also:

https://docs.rs/tokio/0.1.16/tokio/fs/fn.rename.html

and:

https://www.rosettacode.org/wiki/Rename_a_file#Rust

looks like /jelly/src/server.rs might be the place to start... If I end up with something useable I will either add it as a pull request or as notes to the readme depending on how involved it is.

**Comment by ryanmcgrath** [comment]
Eh, project's small right now, your question is fine, no worries.

Does a generic querystring not work? e.g `style.css?q={{ some_timestamp_here }}`

Can never remember if browsers made that trick not work anymore, lol

**Comment by Jieiku** [comment]
OH! let me give that a try, I had not thought of that, thank you!
