### ISSUE TITLE
Logout form button seems to work fine, using a Logout link directs to a blank page.

### ISSUE THREAD

**Issue by Jieiku** [secretkeysio/jelly-actix-web-starter#32]
Logout form button seems to work fine, using a Logout link directs to a blank page.

I modified `templates/dashboard/layout.html`

this goes to blank page:
```html
<a href="/accounts/logout/" title="Logout">Logout</a>
```

the original ones logs you out AND redirects to index:

```html
    <form method="post" action="/accounts/logout/">
        <button type="submit">Logout</button>
    </form>
```

I am still looking for ways to resolve this. searching the source for logout, I see two other files:

`src/accounts/mod.rs`  and  `src/accounts/views/mod.rs`

In `src/accounts/mod.rs` I see that most functions have both a get and a post

```
.service(
                resource("/register/")
                    .route(get().to(views::register::form))
                    .route(post().to(views::register::create_account)),
            )
```

but logout only has the post...

.service(resource("/logout/").route(post().to(views::logout))),

I am assuming this is my problem, and I would need to modify this in order to be able to logout using a link instead of a form?

This is important because forms get styled very differently than links do.

I do not want to put a form element into my sites navigation bar if I can help it.

**Comment by Jieiku** [comment]
The alternative is maybe I can apply a class that over rides the form styles for the logout button in the navigation bar.... so that it appears as a regular link.

**Comment by Jieiku** [comment]
I got this working, I will submit a pull request for it now.

**Comment by ryanmcgrath** [comment]
Woah there... uhhh, don't do this. :)

A logout is a destructive and/or changing action (destroying a session). These actions should never be tied to a `GET` request. This is what the other HTTP methods are for.

You can trick a user into inadvertently loading a link that logs them out (or worse, depending on what you have tied to the `GET`).

The correct pattern (that doesn't rely on JS) is to style a form where the submit button looks like a link. This ties the action to a `POST` and can't be easily triggered by coercing someone to click on a link - and it's why the starter is pre-configured to do that. CSS and JS are more than powerful enough to get different visual behavior/interactions if you need 'em.

Going to close this one because there's no real chance of this pattern changing; providing safe defaults is the goal here.

**Comment by Jieiku** [comment]
Very good to know, I did initially try styling the link to look like the other links and I got it pretty close, with a bit more work I can get it to look right im sure. Thanks @ryanmcgrath

**Comment by Jieiku** [comment]
@ryanmcgrath I am wanting to use an <a href=""> type link, but I want to do so securely. Can you share some more information about this?

I checked a lot of the Big commerce and financial sites and with the exception of bestbuy they all seem to be using <a href> links.

gmail seems includes a timestamp as well as a token as part of the logout link. I am guessing they check these to make sure the logout is a legitimate request?

The target one is particularly interesting.... I wonder how they did that, it looks to link to the root url but it is also the sign out link?

I am thinking there must be a way to safely use an a href link for logging out or these million and billion dollar companies would all be using form buttons for logging out.

gmail:
<a class="gb_Ab gb_Lf gb_Tf gb_He gb_1c" id="gb_71" href="https://accounts.google.com/Logout?hl=en&amp;continue=https://mail.google.com&amp;service=mail&amp;timeStmp=1641708893&amp;secTok=.redacted;ec=redacted" target="_top">Sign out</a>

american express:
<a class="axp-global-header__GlobalHeader__closedLogout___3TWrS axp-global-header__dls-module__dlsBrightBlue___3kaV7" accesskey="4" href="https://www.americanexpress.com/en-us/account/logout"><span>Log Out</span></a>

paypal:
<a class="cw_navbar__secondary-item cw_navbar__secondary-item--text cw_navbar_logout" href="/signout" id="header-logout" name="header-logout" data-name="header-logout" data-pagename="main:header" data-pa-click="header-logout" pa-marked="1">Log Out</a>

target:
<a href="/" class="Link__StyledLink-sc-4b9qcv-0 styles__ListLink-sc-5oc0g9-2 eaEvPH egWFZH" data-ff-lnk-nav-click-text="Sign Out" to="/"><span class="styles__ListItemText-sc-5oc0g9-1 dicGJk">Sign out</span></a>

amazon:
<a id='nav-item-signout' href='/gp/flex/sign-out.html?path=%2Fgp%2Fyourstore%2Fhome&signIn=1&useRedirectOnSuccess=1&action=sign-out&ref_=nav_AccountFlyout_signout' class='nav-link nav-item'><span class='nav-text'>Sign Out</span></a>

ebay:
<a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;lgout=1" _sp="m570.l2622">Sign out</a>

walmart:
<a link-identifier="Generic Name" class="dark-gray db f6 no-underline nowrap desktop-header-flyout-link" href="/account/logout?vid=oaoh">

etsy:
<a role="menuitem" href="https://www.etsy.com/logout.php?ref=hdr_user_menu-signout" class="wt-menu__item wt-display-flex-xs wt-align-items-center wt-justify-content-flex-start wt-pt-xs-1 wt-pb-xs-1 wt-mt-xs-4">

bestbuy: (this one uses a form)
<form name="logoutForm" method="POST" action="/identity/signout?redirect=true" class="js-account-body"><button class="c-button-link account-menu-logout-button" type="submit" id="logout-button">Sign out</button></form>

oreillyauto:
<a data-v-000ed57f="" href="/logout" data-qa="desktop-header-account-popover-sign-out" class="account-dropdown__link account-dropdown__link--sign-out"> Sign Out </a>

napaonline:
<a href="/en/logout" class="button-primary blue">Log Out</a>

**Comment by Jieiku** [comment]
@ryanmcgrath I am wanting to use an <a href=""> type link, but I want to do so securely. Can you share some more information about this?

I checked a lot of the Big commerce and financial sites and with the exception of bestbuy they all seem to be using <a href> links.

gmail seems includes a timestamp as well as a token as part of the logout link. I am guessing they check these to make sure the logout is a legitimate request?

The target one is particularly interesting.... I wonder how they did that, it looks to link to the root url but it is also the sign out link?

I am thinking there must be a way to safely use an a href link for logging out or these million and billion dollar companies would all be using form buttons for logging out.

```
gmail:
<a class="gb_Ab gb_Lf gb_Tf gb_He gb_1c" id="gb_71" href="https://accounts.google.com/Logout?hl=en&amp;continue=https://mail.google.com&amp;service=mail&amp;timeStmp=1641708893&amp;secTok=.redacted;ec=redacted" target="_top">Sign out</a>

american express:
<a class="axp-global-header__GlobalHeader__closedLogout___3TWrS axp-global-header__dls-module__dlsBrightBlue___3kaV7" accesskey="4" href="https://www.americanexpress.com/en-us/account/logout"><span>Log Out</span></a>

paypal:
<a class="cw_navbar__secondary-item cw_navbar__secondary-item--text cw_navbar_logout" href="/signout" id="header-logout" name="header-logout" data-name="header-logout" data-pagename="main:header" data-pa-click="header-logout" pa-marked="1">Log Out</a>

target:
<a href="/" class="Link__StyledLink-sc-4b9qcv-0 styles__ListLink-sc-5oc0g9-2 eaEvPH egWFZH" data-ff-lnk-nav-click-text="Sign Out" to="/"><span class="styles__ListItemText-sc-5oc0g9-1 dicGJk">Sign out</span></a>

amazon:
<a id='nav-item-signout' href='/gp/flex/sign-out.html?path=%2Fgp%2Fyourstore%2Fhome&signIn=1&useRedirectOnSuccess=1&action=sign-out&ref_=nav_AccountFlyout_signout' class='nav-link nav-item'><span class='nav-text'>Sign Out</span></a>

ebay:
<a href="https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&amp;lgout=1" _sp="m570.l2622">Sign out</a>

walmart:
<a link-identifier="Generic Name" class="dark-gray db f6 no-underline nowrap desktop-header-flyout-link" href="/account/logout?vid=oaoh">

etsy:
<a role="menuitem" href="https://www.etsy.com/logout.php?ref=hdr_user_menu-signout" class="wt-menu__item wt-display-flex-xs wt-align-items-center wt-justify-content-flex-start wt-pt-xs-1 wt-pb-xs-1 wt-mt-xs-4">

bestbuy: (this one uses a form)
<form name="logoutForm" method="POST" action="/identity/signout?redirect=true" class="js-account-body"><button class="c-button-link account-menu-logout-button" type="submit" id="logout-button">Sign out</button></form>

oreillyauto:
<a data-v-000ed57f="" href="/logout" data-qa="desktop-header-account-popover-sign-out" class="account-dropdown__link account-dropdown__link--sign-out"> Sign Out </a>

napaonline:
<a href="/en/logout" class="button-primary blue">Log Out</a>
```
