### ISSUE TITLE
Login request takes 8 seconds

### ISSUE THREAD

**Issue by delneg** [secretkeysio/jelly-actix-web-starter#4]
After setting everything up to try and take this app for a spin (and that wasn't easy, especially with #3 not merged and the application requiring me to set literally every single env var in .env before launch), I've come across the problem of very slow login responses (7.5 seconds).

Any idea why that could happen ?
```
INFO  actix_web::middleware::logger > 127.0.0.1:60779 "GET /accounts/verify/ HTTP/1.1" 200 933 "http://127.0.0.1:8000/accounts/register/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0" 0.000454
 INFO  actix_web::middleware::logger > 127.0.0.1:60794 "GET / HTTP/1.1" 200 908 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0" 0.000416
 INFO  actix_web::middleware::logger > 127.0.0.1:60794 "GET /accounts/login/ HTTP/1.1" 200 1231 "http://127.0.0.1:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0" 0.000663
 INFO  sqlx::query                   > /* SQLx ping */; rows: 0, elapsed: 267.350µs
 INFO  sqlx::query                   > SELECT id, name, password, …; rows: 1, elapsed: 3.590ms

SELECT
  id,
  name,
  password,
  is_admin
FROM
  accounts
WHERE
  email = $1

 INFO  actix_web::middleware::logger > 127.0.0.1:60797 "POST /accounts/login/ HTTP/1.1" 400 1329 "http://127.0.0.1:8000/accounts/login/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0" 7.477480
 INFO  sqlx::query                   > /* SQLx ping */; rows: 0, elapsed: 177.526µs
 INFO  sqlx::query                   > SELECT id, name, password, …; rows: 1, elapsed: 316.032µs

SELECT
  id,
  name,
  password,
  is_admin
FROM
  accounts
WHERE
  email = $1

 INFO  actix_web::middleware::logger > 127.0.0.1:60800 "POST /accounts/login/ HTTP/1.1" 400 1329 "http://127.0.0.1:8000/accounts/login/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0" 7.313738
 ```

**Comment by ryanmcgrath** [comment]
>and that wasn't easy, especially with #3 not merged and the application requiring me to set literally every single env var in .env before launch

You know, this kind of tone is probably why people burn out on open source. This is all offered as-is, and the README disclaimer (which I'll repeat below) even notes that you will probably have to tinker with it for your own needs.

>A disclaimer: this is used internally, and while it's very usable, it might not be perfect. You might need to tweak a thing or two. Don't be shocked if you need to alter jelly for your own needs. Pull requests for things that should be "standard" are welcome.

I'm gonna be super, ultra, very evidently clear here: this is explicitly _not_ an "app", it's a starter that you use to customize for whatever. ENV keys are required because _my_ use case _can't_ have them fail, and that issue you're referring to has a response from me indicating that there's no point in merging it because those templates are not Tera templates. Users who don't need the email functionality should just delete them or something, but I guess I'll just move the folder out of `templates` to make this more clear.

As to your actual issue: 3 seconds seems very odd, but I'm not sure what that'd be coming from (and off the top of my head, that SQL query is repeated a few lines down with very different timings). I built this on a 10.15.7 local setup, and didn't have this issue, so... without more information it's hard to say more. I'd be digging into that `SELECT` call to see what's happening.

**Comment by delneg** [comment]
> > and that wasn't easy, especially with #3 not merged and the application requiring me to set literally every single env var in .env before launch
> 
> You know, this kind of tone is probably why people burn out on open source. This is all offered as-is, and the README disclaimer (which I'll repeat below) even notes that you will probably have to tinker with it for your own needs.
> 
> > A disclaimer: this is used internally, and while it's very usable, it might not be perfect. You might need to tweak a thing or two. Don't be shocked if you need to alter jelly for your own needs. Pull requests for things that should be "standard" are welcome.
> 
> I'm gonna be super, ultra, very evidently clear here: this is explicitly _not_ an "app", it's a starter that you use to customize for whatever. ENV keys are required because _my_ use case _can't_ have them fail, and that issue you're referring to has a response from me indicating that there's no point in merging it because those templates are not Tera templates. Users who don't need the email functionality should just delete them or something, but I guess I'll just move the folder out of `templates` to make this more clear.
> 
> As to your actual issue: 3 seconds seems very odd, but I'm not sure what that'd be coming from (and off the top of my head, that SQL query is repeated a few lines down with very different timings). I built this on a 10.15.7 local setup, and didn't have this issue, so... without more information it's hard to say more. I'd be digging into that `SELECT` call to see what's happening.

Hello, and thanks for the quick response.
First of all, let me apologize for upsetting you with my issue. I didn't intent to offend you in any way, it's sometimes unclear for me as a non-native english speaker how to put the sentence so that it's not taken personally.

Thanks for clarifying on the Tera templates issue, I guess that's not a big problem.

As for the response time, it's OK if you didn't have similar problems, maybe it has something to do with my particular setup or configuration issue.

Just to be clear - this is an awesome repository that you've built and thanks a lot for your work!

**Comment by ryanmcgrath** [comment]
It's cool - and I totally recognize the language aspect, so I also apologize if I snapped back too harshly. Open source is rough sometimes, lol...

If you find something off with that `SELECT` command that'd cause it to consume time like that, I'm definitely open to patches, so just let me know. I can keep this issue open for a week or so in case you find something.

**Comment by ryanmcgrath** [comment]
@delneg Issue #14 might interest you - were you running in full release mode when testing this? The user there was able to seemingly hit more expected timing, curious if it works for you.

**Comment by ryanmcgrath** [comment]
I'm gonna close this as it's being tracked/investigated in #14. Super appreciate any other insights that you might be able to provide.

**Comment by Jieiku** [comment]
It is almost certainly the password hashing fuctions that caused this, when you cargo build if you use --release it should resolve this. This is what I found in my testing and I found another related post here: https://github.com/Racum/rust-djangohashers/issues/5
