### ISSUE TITLE
bad master key length: expected >= 32 bytes, found 4

### ISSUE THREAD

**Issue by samarthc-rapid** [secretkeysio/jelly-actix-web-starter#43]
Hi, I am trying to set up the project according to the instructions but facing an error

`\Rust\jelly-actix-web-starter> cargo run RUST_BACKTRACE=FULL

    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
     Running `target\debug\webserver.exe RUST_BACKTRACE=FULL`
 INFO  actix_server::builder > Starting 4 workers
 INFO  actix_server::builder > Starting "actix-web-service-127.0.0.1:17001" service on 127.0.0.1:17001
thread 'actix-rt:worker:0' panicked at 'bad master key length: expected >= 32 bytes, found 4', C:\Users\Asus\.cargo\registry\src\github.com-1ecc6299db9ec823\cookie-0.14.4\src\secure\key.rs:88:13`

**Comment by samarthc-rapid** [comment]
Does master key here refer to my Postgres master key? Do i need to change it to more than 32 characters?

**Comment by ryanmcgrath** [comment]
No, it's a key used for encrypting things like session data and so on. If you have Python installed, you can do something like:

``` sh
python -c "import secrets; print(secrets.token_urlsafe())"
```

to generate one.

**Comment by samarthc-rapid** [comment]
got it thanks
