### ISSUE TITLE
Setting up postmark

### ISSUE THREAD

**Issue by samarthc-rapid** [secretkeysio/jelly-actix-web-starter#44]
I have inserted the postmark API-key and SMTP settings from the default transaction stream in my .env file but cant get it to work.

logs -  
```
INFO  background_jobs_core::processor_map > Job 9b948299-d7c5-47cf-b90b-c40483d88e6a SendAccountOddRegisterAttemptEmailJob errored Error performing job: No email provider configured 0.004524 
```

my code analyze tells me "code is inactive due to #[cfg] directives: feature = "email-postmark" is disabled", How can I enable this feature?

**Comment by Jieiku** [comment]
how are you running your project?

I run mine like this:

```
cargo build --release --no-default-features --features "production","argon2,"jelly/email-smtp"
./target/release/webserver
```

**Comment by samarthc-rapid** [comment]
Thanks, I got it to work using `cargo build --release --no-default-features --features "production","jelly/email-postmark"`
